### PR TITLE
fix concat referenced in ensure_resource

### PR DESCRIPTION
**Pull request by trefzer**
concat resource should be referenced without :: with ensure_resources.

### CODE REVIEW

**Comment by johanfleury** [comment]
Thank you for your PR. Your contribution to this project is really well appreciated.

I don't understand the issue you're facing here. The usage of a fully qualified resource name seems to work on my side (I use multiple stub-zones and everything goes fine).

Could you tell me more about what you're trying to fix here?

**Comment by trefzer** [comment]
Well I had errors which I could fix by taking away the ::, but I do not have any clue why.
I will investigate some more about that. Can you provide me with the puppet version and concat version you are using for your'e working system ?

**Comment by johanfleury** [comment]
I use Puppet version `5.4` on Debian (through PuppetLabs' packages) and the latest version of `concat` (currently it's `4.2.0`):

```
# dpkg -l | grep -e puppet-agent -e puppetserver
ii  puppet-agent                  5.4.0-1stretch                 amd64        The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
ii  puppetserver                  5.2.0-1stretch                 all          no description given
# grep '"version":' /etc/puppetlabs/code/environments/production/modules/concat/metadata.json
  "version": "4.2.0",
```

**Comment by johanfleury** [comment]
Also, could you please provide us with more details on what happens on your side (any error message, or something)?

**Comment by trefzer** [comment]
ok. that is probably a way to investigate. I also use debian, but debian packages on puppet 4.8.2-5
I use concat version 3.0.0.
The error I get in this constellation is:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Invalid tag '::concat' at /etc/puppet/environments/dev_unbound/modules/unbound/manifests/stub_zone.pp:13:3 at /etc/puppet/environments/dev_unbound/modules/unbound/manifests/config.pp:38 on node ****`

I get the same error if I use concat 4.2.0, so this seems to be an issue with the puppet version !

**Comment by trefzer** [comment]
ok. I found it !
using puppetlabs-stdlib (where ensure_resource comes from) in version 4.16.0 get's the error.
with version 4.17.0 I do not get the error. I could not figure out about the exact commit that fixes. But anyway.
You should either use my fix or bump the required version of puppetlabs-stdlib in metadata.json.

**Comment by trefzer** [comment]
ok I updated this commit to include the case in the commit message.
since it's the same line fixing, I also include the patch for #7 if you merge #7 first, then rebase should work.
Or merge this one and abort #7 ;)

**Comment by johanfleury** [comment]
Good find.

As I prefer to use fully qualified resource names in my code I'd rather bump supported stdlib version to `4.17` and keep using this declaration syntax.

I don't think there are breaking changes between version `4.6` and version `4.17` and it was released 9 months ago.

If you agree with that, could you please update your PR with the `metadata.json` fix and remove changes made to `ensure_resource` statements?

**Comment by trefzer** [comment]
done

**Comment by johanfleury** [comment]
Watch out, you changed the puppet required version not the stdlib one.

**Comment by trefzer** [comment]
shame on me ;) 
now it should be good

**Comment by trefzer** [comment]
can you release a new version after merging ?
Thanks

**Comment by johanfleury** [comment]
That's what I planed to do :)

**Pull request merged**
